/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './assets/*.js',
    './layout/*.liquid',
    './templates/*.json',
    './templates/customers/*.liquid',
    './sections/*.liquid',
    './snippets/*.liquid',
  ],
  safelist: [
    'pt-4',
    'pt-8',
    'pt-12',
    'pt-16',
    'pt-20',
    'pt-24',
    'pt-28',
    'pt-32',
    'pt-36',
    'pt-40',
    'pb-4',
    'pb-8',
    'pb-12',
    'pb-16',
    'pb-20',
    'pb-24',
    'pb-28',
    'pb-32',
    'pb-36',
    'pb-40',
    'mt-8',
    'mt-16',
    'mt-24',
    'mt-32',
    'mt-40',
    'mb-8',
    'mb-16',
    'mb-24',
    'mb-32',
    'mb-40',
    'md:pt-8',
    'md:pt-16',
    'md:pt-24',
    'md:pt-32',
    'md:pt-40',
    'md:pt-48',
    'md:pt-56',
    'md:pt-64',
    'md:pt-72',
    'md:pt-80',
    'md:pb-8',
    'md:pb-16',
    'md:pb-24',
    'md:pb-32',
    'md:pb-40',
    'md:pb-48',
    'md:pb-56',
    'md:pb-64',
    'md:pb-72',
    'md:pb-80',
    'object-[50%_100%]',
    'object-[50%_90%]',
    'object-[50%_80%]',
    'object-[50%_70%]',
    'object-[50%_60%]',
    'object-[50%_50%]',
    'object-[50%_40%]',
    'object-[50%_30%]',
    'object-[50%_20%]',
    'object-[50%_10%]',
    'object-[50%_0%]',
    'object-[0%]',
    'w-16',
    'w-24',
    'w-32',
    'delay-[100ms]',
    'delay-[300ms]',
    'delay-[500ms]',
    'delay-[700ms]',
    'delay-[900ms]',
    'delay-[1100ms]',
    'delay-[1300ms]',
    'delay-[1500ms]',
    'delay-[1700ms]',
    'delay-[1900ms]',
    'delay-[2100ms]',
    'delay-[2300ms]',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'md:!text-[26px]',
    '!text-[28px]',
    'md:col-span-3',
    '!font-header',
    'md:aspect-[3/4]',
  ],
  theme: {
    extend: {
      colors: {
        // Add custom colors if needed
        primary: '#ff6347',
        secondary: '#4a90e2',
      },
      fontFamily: {
        // Add custom fonts if needed
        sans: ['Arial', 'sans-serif'],
      },
    },
  },
  plugins: [
    // Add any Tailwind plugins you might be using
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
  ],
};
